### ISSUE TITLE
Hexo 怎么使用搜索控件

### ISSUE THREAD

**Issue by devtofu** [androiddevelop/CodeboyBlog#1]
对 js 不是太熟，hexo 搭建的怎么使用这个搜索控件呢？

**Comment by androiddevelop** [comment]
这两天我看下怎么加入对hexo的支持

**Comment by androiddevelop** [comment]
https://github.com/androiddevelop/hexo-search

**Comment by devtofu** [comment]
加上了，谢谢。   对前端这块不是很懂，顺便问一下，用 npm 安装的插件装在哪了？ 看到 hexo 目录多了两个文件， db.json package.json 。

**Comment by androiddevelop** [comment]
安装在了node_modules文件夹中

**Comment by devtofu** [comment]
谢谢。
