### ISSUE TITLE
[Q]  代码行号的问题怎么解决?

### ISSUE THREAD

**Issue by Guang1234567** [androiddevelop/CodeboyBlog#2]
Hello dev:

代码行号的问题怎么解决?  我看你的blog 的代码没有行号,  但在  _config,yml 配置 "行号功能", 请问这是什么情况, 能否抽空告知一下, 谢谢

**Comment by androiddevelop** [comment]
这个和主题有一定的关系，我研究下，怎么添加行号。

**Comment by androiddevelop** [comment]
已经支持。样式可以参考https://www.codeboy.me/2017/02/07/head-first-singleton/

**Comment by Guang1234567** [comment]
多谢, 我看看先.
