### ISSUE TITLE
怎么添加GitTalk评论插件啊？

### ISSUE THREAD

**Issue by DFVSQY** [androiddevelop/CodeboyBlog#3]
网易云跟帖关闭了，想换用[GitTalk](https://github.com/gitalk/gitalk)评论插件，但是直接替换网易云那块的代码文章就不能正常排版了，对于Web非常不熟悉，希望作者把网易云跟帖换成GitTalk评论系统以供参考，谢谢！

**Comment by androiddevelop** [comment]
可以使用畅言，http://changyan.kuaizhan.com，我这边换一下

**Comment by DFVSQY** [comment]
搜狐帐号不常用，考虑到受众群体及国内服务的持续性问题，我想使用一个GitHub帐号的评论系统，如若有时间也烦请作者不吝赐教，给本人提供一个Demo示例。多谢！

**Comment by androiddevelop** [comment]
可以参考 https://jacobpan3g.github.io/cn/2017/07/17/gitment-in-jekyll/ 尝试添加。

**Comment by androiddevelop** [comment]
项目里评论已经更换为了畅言。 github的可以参考上文文章。

**Comment by DFVSQY** [comment]
@androiddevelop  帮忙看一下，我把post.html文件里面那块网易云跟帖的代码换成了gittalk，如下图：
![image](https://user-images.githubusercontent.com/8075421/39579063-65c95a3e-4f18-11e8-8716-102a39cc22e7.png)

但是预览文章时发现整个排版乱了，这个需要怎么修改一下布局呢？还是说这本身是gittalk的原因？

![image](https://user-images.githubusercontent.com/8075421/39579184-b097f732-4f18-11e8-9525-04ec1afa62a9.png)

**Comment by DFVSQY** [comment]
@androiddevelop  解决了，原来是保存时自动格式化html文件导致的。

**Comment by androiddevelop** [comment]
赞一个
