### ISSUE TITLE
博客文章对于markdown的inline code不支持了

### ISSUE THREAD

**Issue by DFVSQY** [androiddevelop/CodeboyBlog#4]
具体效果可以参考你的[Android文章链接](https://blogtest.codeboy.me/2015/07/28/android-trick/)，代码段中写中文也不行。

**Comment by DFVSQY** [comment]
@androiddevelop 有时间麻烦作者帮忙看一下，这个还是很影响写文章的。 多谢！

**Comment by DFVSQY** [comment]
@androiddevelop 我自己摸索出一个方法，只要把代码行号的功能取消掉就可以，具体做法把`_config.yml`文件的`line_numbers:      inline`注释掉即可。

**Comment by androiddevelop** [comment]
赞一个
